authentication:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}
server:
    port: ${PORT:8080}
spring:
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
        datasource:
            url: ${POSTGRES_URL}
            username: ${POSTGRES_USERNAME}
            password: ${POSTGRES_PASSWORD}
springdoc:
    swagger-ui:
        path: /swagger-ui.html
